USE PC
SELECT AVG(SPEED) AS AVG_SPEED FROM PC

SELECT MAKER, AVG(SCREEN) AS AVG_SCREEN FROM LAPTOP
	JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL 
	GROUP BY MAKER

SELECT AVG(SPEED)AS AVG_SPEED FROM LAPTOP WHERE PRICE>=1000

SELECT ROUND(AVG(PRICE),2) AS AVG_PRICE FROM PC
	JOIN PRODUCT ON PC.MODEL = PRODUCT.MODEL
	WHERE MAKER = 'A'

SELECT AVG(P.PRICE) AS AVG_PRICE FROM
	(SELECT PRICE FROM PC
		JOIN PRODUCT ON PC.MODEL = PRODUCT.MODEL
		WHERE MAKER = 'B'
	UNION
	SELECT PRICE FROM LAPTOP
		JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL
		WHERE MAKER = 'B') AS P

SELECT SPEED, AVG(PRICE) AS AVG_PRICE FROM PC GROUP BY SPEED

SELECT MAKER FROM PRODUCT 
	JOIN PC ON PC.MODEL = PRODUCT.MODEL
	GROUP BY MAKER
	HAVING COUNT(PC.MODEL)>=3

SELECT MAKER FROM PRODUCT 
	JOIN PC ON PC.MODEL=PRODUCT.MODEL
	WHERE PRICE>=(SELECT MAX(PRICE) FROM PC)

SELECT AVG(PRICE) AS AVG_PRICE FROM PC
	GROUP BY SPEED
	HAVING SPEED>=800

SELECT AVG(HD) AS AVG_HD FROM PC 
	JOIN PRODUCT AS P ON PC.MODEL=P.MODEL
	WHERE P.MAKER IN (SELECT MAKER FROM PRODUCT WHERE TYPE='Printer')

SELECT SCREEN, (MAX(PRICE) - MIN(PRICE)) AS DIF FROM LAPTOP GROUP BY SCREEN

USE SHIPS
SELECT COUNT(*) AS COUNT_SHIPS FROM CLASSES

SELECT AVG(NUMGUNS) AS AVG_GUNS FROM CLASSES AS C
	JOIN SHIPS AS S ON S.CLASS=C.CLASS

SELECT C.CLASS, MIN(LAUNCHED) AS FIRST_YEAR, MAX(LAUNCHED) AS LAST_YEAR FROM CLASSES AS C
	JOIN SHIPS AS S ON S.CLASS=C.CLASS
	GROUP BY C.CLASS

SELECT CLASS, COUNT(O.SHIP) AS COUNT FROM SHIPS
	LEFT JOIN OUTCOMES AS O ON NAME=SHIP AND RESULT='SUNK'
	GROUP BY CLASS 

SELECT C.CLASS, COUNT(*) AS COUNT FROM
 (SELECT CLASS, COUNT(NAME) AS COUNT FROM SHIPS
	GROUP BY CLASS 
	HAVING COUNT(NAME)>=4 ) AS C
	JOIN SHIPS AS S ON S.CLASS=C.CLASS
	JOIN OUTCOMES AS O ON S.NAME=SHIP
	WHERE RESULT='SUNK'
	GROUP BY C.CLASS

SELECT COUNTRY, AVG(DISPLACEMENT) AS AVG_D FROM CLASSES GROUP BY COUNTRY

USE movies
SELECT STARNAME, COUNT(TITLE) AS MOVIES FROM STARSIN JOIN MOVIE ON MOVIETITLE=TITLE
	GROUP BY STARNAME

SELECT NAME, COUNT(TITLE) AS MOVIES FROM MOVIESTAR
LEFT JOIN STARSIN ON NAME=STARNAME
LEFT JOIN MOVIE ON MOVIETITLE=TITLE
GROUP BY NAME

SELECT STARNAME FROM STARSIN
	JOIN MOVIE ON TITLE=MOVIETITLE


