USE movies

SELECT NAME FROM MOVIESTAR AS STAR
	WHERE NAME IN (SELECT NAME FROM MOVIEEXEC WHERE NETWORTH>10000000) AND GENDER='F'

SELECT NAME FROM MOVIESTAR
	WHERE NAME NOT IN (SELECT NAME FROM MOVIEEXEC)

USE pc

SELECT DISTINCT MAKER FROM PRODUCT
	WHERE MODEL IN (SELECT MODEL FROM PC WHERE SPEED>=500)

SELECT * FROM LAPTOP 
	WHERE speed<ALL(SELECT SPEED FROM PC)

SELECT P.MODEL FROM PRODUCT AS P
	JOIN (SELECT MODEL, PRICE FROM PC
			UNION
		SELECT MODEL, PRICE FROM LAPTOP
			UNION
		SELECT MODEL, PRICE FROM PRINTER) AS M
			ON M.MODEL = P.MODEL
			WHERE M.PRICE>=ALL((SELECT PRICE FROM PC
								UNION
							SELECT PRICE FROM LAPTOP
								UNION
							SELECT PRICE FROM PRINTER))

SELECT MAKER FROM PRODUCT
	JOIN PRINTER ON PRODUCT.MODEL= PRINTER.MODEL
	WHERE PRICE<=ALL(SELECT PRICE FROM PRINTER WHERE color='y') and PRODUCT.MODEL IN (SELECT MODEL FROM PRINTER WHERE color='y')

SELECT MAKER FROM PRODUCT 
	JOIN (SELECT MODEL,SPEED, RAM FROM PC 
		WHERE RAM <= ALL(SELECT RAM FROM PC) AND SPEED>=ALL(SELECT SPEED FROM PC WHERE RAM<=ALL(SELECT RAM FROM PC))) AS P ON P.MODEL=PRODUCT.MODEL
		
USE SHIPS

SELECT DISTINCT COUNTRY FROM CLASSES
 WHERE NUMGUNS>=ALL(SELECT NUMGUNS FROM CLASSES)

SELECT NAME FROM SHIPS
	WHERE CLASS IN (SELECT CLASS FROM CLASSES WHERE BORE=16)

SELECT NAME FROM BATTLES
	WHERE NAME IN(SELECT BATTLE FROM OUTCOMES WHERE SHIP IN (SELECT NAME FROM SHIPS WHERE CLASS='Kongo'))

SELECT CLASS FROM CLASSES AS C
	WHERE NUMGUNS>= ALL(SELECT NUMGUNS FROM CLASSES AS D WHERE C.BORE = D.BORE)

SELECT NAME FROM SHIPS 
	JOIN CLASSES AS C ON SHIPS.CLASS = C.CLASS
	WHERE C.NUMGUNS>=ALL(SELECT NUMGUNS FROM CLASSES AS C1 WHERE C.BORE=C1.BORE)


