USE MOVIES
/*SELECT TIME, COUNT(NAME) AS NUM FROM (SELECT CASE WHEN YEAR(BIRTHDATE)<1960 THEN 'bf1960'
		WHEN YEAR(BIRTHDATE)>=1960 AND YEAR(BIRTHDATE)<1970 THEN '60S' 
		WHEN YEAR(BIRTHDATE)>=1970 AND YEAR(BIRTHDATE)<1980 THEN '70S'
		WHEN YEAR(BIRTHDATE)<=1980 THEN 'AF1980'
		END AS TIME, NAME 
		FROM MOVIESTAR) S
	GROUP BY S.TIME

USE SHIPS
SELECT BATTLE FROM OUTCOMES
	JOIN SHIPS ON NAME=SHIP
	JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
	GROUP BY BATTLE
	HAVING SUM(CASE WHEN NUMGUNS<=9 THEN 1 ELSE 0 END)>=3 AND SUM(CASE WHEN NUMGUNS<=9 AND RESULT ='ok' THEN 1 ELSE 0 END)>=2

SELECT BATTLE, COUNT(SHIP) AS SUNK_USA_SHIPS FROM OUTCOMES
	JOIN SHIPS ON NAME=SHIP	
	JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
	WHERE RESULT = 'sunk' AND COUNTRY='USA'
	GROUP BY BATTLE

SELECT DISTINCT BATTLE FROM OUTCOMES
	JOIN SHIPS ON NAME=SHIP	
	JOIN CLASSES AS C ON SHIPS.CLASS=C.CLASS
	GROUP BY BATTLE, COUNTRY 
	HAVING COUNT(COUNTRY)>=3

SELECT DISTINCT C.CLASS, LAUNCHED FROM CLASSES AS C
	LEFT JOIN SHIPS AS S ON S.CLASS=C.CLASS
	WHERE LAUNCHED <1921

SELECT NAME, SUM(CASE RESULT WHEN 'damaged' THEN 1 ELSE 0 END) AS DAMAGED FROM SHIPS
	LEFT JOIN OUTCOMES ON SHIP=NAME
	GROUP BY NAME

SELECT COUNTRY, COUNT(NAME) AS NUMSHIPS, SUM(CASE RESULT WHEN 'sunk' THEN 1 ELSE 0 END) AS SUNK FROM CLASSES AS C	
	JOIN SHIPS AS S ON S.CLASS=C.CLASS
	LEFT JOIN OUTCOMES ON NAME=SHIP
	GROUP BY COUNTRY 

SELECT COUNTRY, SUM(CASE RESULT WHEN 'damaged' THEN 1 ELSE 0 END) AS DAMAGED, SUM(CASE RESULT WHEN 'sunk' THEN 1 ELSE 0 END) AS SUNK FROM CLASSES AS C	
	LEFT JOIN SHIPS AS S ON S.CLASS=C.CLASS
	LEFT JOIN OUTCOMES ON NAME=SHIP
	GROUP BY COUNTRY 

SELECT C.CLASS, SUM(CASE RESULT WHEN 'ok' THEN 1 ELSE 0 END) FROM CLASSES AS C
	JOIN SHIPS AS S ON S.CLASS=C.CLASS
	LEFT JOIN OUTCOMES ON NAME=SHIP
	GROUP BY C.CLASS
	HAVING COUNT(DISTINCT NAME)>=3 AND SUM(CASE RESULT WHEN 'ok' THEN 1 ELSE 0 END)>0*/

	/*SELECT NAME, BIRTHDATE, SUM(SELECT STUDIONAME FROM MOVIE JOIN STARSIN ON MOVIETITLE=TITLE) FROM MOVIESTAR
		JOIN STARSIN ON NAME=STARNAME*/
	--SELECT STARNAME, MAX( SELECT  STUDIONAME) FROM MOVIE JOIN STARSIN ON MOVIETITLE=TITLE GROUP BY STARNAME, 
	
	


