USE PC

BEGIN TRANSACTION
--INSERT INTO MovieStar (name, gender, BIRTHDATE) VALUES ('Nicole Kidman', 'F', '1967-06-20' );
--UPDATE MOVIE SET PRODUCERC#=NULL WHERE PRODUCERC# IN (SELECT CERT# FROM MOVIEEXEC WHERE NETWORTH<10000000)

--DELETE FROM MOVIEEXEC WHERE NETWORTH<10000000;

--UPDATE STARSIN SET STARNAME=NULL WHERE STARNAME IN (SELECT NAME FROM MOVIESTAR WHERE ADDRESS=NULL)

--DELETE FROM MOVIESTAR WHERE ADDRESS=NULL;

--INSERT INTO PRODUCT VALUES ('C', 1100, 'PC');
--INSERT INTO PC VALUES (12 , '1100', 2400, 2048, 500, '52x', 299);
--DELETE FROM PC WHERE  MODEL= 1100;
--DELETE FROM PRODUCT WHERE MAKER='C' AND MODEL= 1100 AND TYPE= 'PC';

/*INSERT INTO LAPTOP(CODE ,MODEL, SPEED, RAM, HD, PRICE, SCREEN)
SELECT DISTINCT CODE + 100, MODEL, SPEED, RAM, HD, PRICE +500, 15
FROM PC;*/

/*DELETE FROM LAPTOP
WHERE MODEL IN (SELECT DISTINCT MODEL
FROM product
WHERE MAKER
 NOT IN (SELECT MAKER
 FROM product WHERE TYPE LIKE 'Printer'));*/

 --UPDATE PRODUCT SET MAKER ='A' WHERE MAKER='B'
 --UPDATE PC SET PRICE=PRICE*2, HD = HD+20
--UPDATE LAPTOP SET SCREEN=SCREEN+1 WHERE MODEL IN (SELECT MODEL FROM PRODUCT WHERE MAKER='B')
