USE movies
SELECT DISTINCT NAME, STARNAME FROM STUDIO
	JOIN MOVIE ON NAME=STUDIONAME
	LEFT JOIN STARSIN ON TITLE = MOVIETITLE

SELECT DISTINCT NAME FROM MOVIEEXEC 
    JOIN MOVIE ON CERT#=PRODUCERC#
	JOIN STARSIN ON TITLE=MOVIETITLE AND STARNAME='Harrison Ford'

SELECT NAME FROM MOVIESTAR
	JOIN STARSIN ON NAME=STARNAME
	JOIN MOVIE ON MOVIETITLE=TITLE AND STUDIONAME='MGM'
	WHERE GENDER='f'
--MY ATTEMPT
SELECT NAME, TITLE FROM MOVIEEXEC
	RIGHT JOIN MOVIE ON PRODUCERC#=CERT#
	JOIN(SELECT CERT# FROM MOVIEEXEC
		 JOIN MOVIE ON CERT#=PRODUCERC# WHERE TITLE LIKE 'Star Wars%') AS M ON M.CERT#=PRODUCERC#
--THE BETTER IDEA
SELECT NAME, TITLE FROM MOVIEEXEC
	JOIN MOVIE ON PRODUCERC#=CERT#
	WHERE CERT# IN (SELECT PRODUCERC# FROM MOVIE WHERE TITLE LIKE 'Star Wars%')

SELECT TITLE, YEAR, P.NAME FROM MOVIE
	LEFT JOIN MOVIEEXEC AS P ON PRODUCERC#=CERT#

SELECT TITLE, YEAR, P.NAME AS PRODUCER_NAME, S.NAME AS STUDIO_NAME, S.ADDRESS AS STUDIO_ADDRESS FROM MOVIE
	LEFT JOIN MOVIEEXEC AS P ON PRODUCERC#=CERT#
	LEFT JOIN STUDIO AS S ON STUDIONAME=S.NAME

SELECT NAME FROM MOVIESTAR
	WHERE NAME NOT IN(SELECT STARNAME FROM STARSIN)

SELECT NAME FROM STARSIN
	RIGHT JOIN MOVIESTAR ON NAME=STARNAME 
	WHERE MOVIETITLE IS NULL
	

USE PC
--???
SELECT R.MODEL, P.PRICE FROM PRODUCT AS R
	LEFT JOIN PC AS P ON R.MODEL=P.MODEL

SELECT MAKER, P.MODEL, P.TYPE FROM PRODUCT AS P
	LEFT JOIN PC ON PC.MODEL = P.MODEL AND PC.CODE IS NULL
UNION
SELECT MAKER, P.MODEL, P.TYPE FROM PRODUCT AS P
	LEFT JOIN LAPTOP AS L ON L.MODEL = P.MODEL AND L.CODE IS NULL
UNION
SELECT MAKER, P.MODEL, P.TYPE FROM PRODUCT AS P
	LEFT JOIN PRINTER AS PR ON PR.MODEL = P.MODEL AND PR.CODE IS NULL 

USE SHIPS

SELECT NAME, COUNTRY, NUMGUNS, LAUNCHED FROM SHIPS
	LEFT JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS

SELECT SHIPS.NAME FROM SHIPS
	JOIN OUTCOMES ON SHIP = SHIPS.NAME
	JOIN BATTLES ON BATTLES.NAME = BATTLE
	WHERE DATE=1942
